
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# To check configuration from Hassio.local:8123:
#       go to Configuration > General > Configuration validation > check config
# If config is valid, reload Home Assistant server:
#       go to Configuration > General > Server management > restart

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

lovelace:
  mode: yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

stream:

logger:
  default: warn
  logs:
    homeassistant.components.shell_command: debug
    homeassistant.components.switch: debug
    homeassistant.components.stream: debug
    homeassistant.components.amcrest: debug
    homeassistant.components.http: debug

switch:
  - platform: wake_on_lan
    name: "Chopper"
    mac: !secret chopper_mac
    host: !secret chopper_ip
    turn_off:
      service: shell_command.turn_off_chopper

shell_command:
    turn_off_chopper: "ssh -i /config/ssh/id_rsa hass@chopper 'sudo poweroff'; echo 'done'"

amcrest:
  - host: !secret babymon_ip
    username: !secret babymon_username
    password: !secret babymon_password
    name: babymon
    binary_sensors:
      - motion_detected
    sensors:
      - sdcard
      - ptz_preset
    stream_source: rtsp
    resolution: high
